# utils/pdf.py

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
import textwrap
import os
from datetime import datetime


def create_pdf(path, listing, fixed, risky, citations, city=None, logo_path="assets\PetClause_AI_logo.jpg"):
    c = canvas.Canvas(path, pagesize=letter)
    width, height = letter
    y = height - 50

    # ---------------------------
    # LOGO
    # ---------------------------
    if os.path.exists(logo_path):
        try:
            logo = ImageReader(logo_path)
            c.drawImage(logo, 50, y - 40, width=140, preserveAspectRatio=True, mask='auto')
            y -= 60
        except Exception:
            y -= 20
    else:
        y -= 20

    # ---------------------------
    # TITLE
    # ---------------------------
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, y, "PetClause AI – Compliance Report")
    y -= 30

    # Jurisdiction
    if city:
        c.setFont("Helvetica-Bold", 13)
        c.drawString(50, y, f"Jurisdiction Analyzed: {city}")
        y -= 20

    # Horizontal line
    c.setStrokeColor(colors.grey)
    c.setLineWidth(1)
    c.line(50, y, width - 50, y)
    y -= 30

    # ---------------------------
    # SECTION: Risky Clauses
    # ---------------------------
    def section_header(title):
        nonlocal y
        c.setFont("Helvetica-Bold", 15)
        c.setFillColor(colors.black)
        c.drawString(50, y, title)
        y -= 15
        c.setStrokeColor(colors.lightgrey)
        c.setLineWidth(0.7)
        c.line(50, y, width - 50, y)
        y -= 20

    section_header("⚠️ Risky Clauses Identified")

    c.setFont("Helvetica", 12)

    if risky:
        for r in risky:
            for line in textwrap.wrap(r, 95):
                c.drawString(60, y, f"• {line}")
                y -= 15
                if y < 70:
                    c.showPage()
                    y = height - 50
    else:
        c.drawString(60, y, "No harmful or illegal phrases detected.")
        y -= 20

    y -= 20

    # ---------------------------
    # SECTION: Improved Listing
    # ---------------------------
    section_header("🛠️ Legally Improved / Corrected Listing")

    for line in textwrap.wrap(fixed, 95):
        c.drawString(60, y, line)
        y -= 15
        if y < 70:
            c.showPage()
            y = height - 50

    y -= 20

    # ---------------------------
    # SECTION: Legal Citations
    # ---------------------------
    section_header("📚 Legal Citations Used in Evaluation")

    if citations:
        for cite in citations:
            for line in textwrap.wrap(cite, 95):
                c.drawString(60, y, f"• {line}")
                y -= 15
                if y < 70:
                    c.showPage()
                    y = height - 50
    else:
        c.drawString(60, y, "No citations returned from the legal model.")
        y -= 20

    y -= 40

    # ---------------------------
    # FOOTER
    # ---------------------------
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    footer_text = f"Generated by PetClause AI on {datetime.now().strftime('%Y-%m-%d %H:%M %Z')}"
    c.drawString(50, 30, footer_text)

    c.save()
